
SELECT 'No. of Entries in BOOK:', COUNT(*) FROM BOOK;
SELECT 'No. of Entries in BOOK_AUTHORS:', COUNT(*) FROM BOOK_AUTHORS;
SELECT 'No. of Entries in BOOK_COPIES:', COUNT(*) FROM BOOK_COPIES;
SELECT 'No. of Entries in BOOK_LOANS:', COUNT(*) FROM BOOK_LOANS;
SELECT 'No. of Entries in BORROWER:', COUNT(*) FROM BORROWER;
SELECT 'No. of Entries in PUBLISHER:', COUNT(*) FROM PUBLISHER;
SELECT 'No. of Entries in LIBRARY_BRANCH:', COUNT(*) FROM LIBRARY_BRANCH;

